#!/bin/bash
# cf.: https://github.blog/2011-11-10-git-io-github-url-shortener/

# $ curl -i https://git.io -F "url=https://github.com/..."
# HTTP/1.1 201 Created
# Location: https://git.io/abc123<Paste>

# vanity url:
# $ curl -i https://git.io -F "url=https://github.com/technoweenie" -F "code=t"
# HTTP/1.1 201 Created
# Location: https://git.io/t

 #Set the color
magenta=$(tput setaf 5)

 #Resets the style
reset=`tput sgr0`

 #Color-echo. Improved. [Thanks @joaocunha; cc: @nnja]
 #arg $1 = message
 #arg $2 = Color
cecho() {
  echo "${2}${1}${reset}"
  return
}

if [[ $# == 2 && $2 =~ '[a-zA-Z]' ]] ; then
  curl -i https://git.io -F "url=${1}" -F "code=${2}"
elif [[ $# == 1 ]] ; then
  curl -i https://git.io -F "url=${1}"
else
  cecho "Invalid input." $magenta
  exit 1
fi
